In [4]:
import numpy as np

a=np.array([1,2])

y=a.copy()  #bu fonksiyon sayesinde a arrayini kopyalarız ve yeni array artık a arrayinden farklı memoryde tutulur.Bu sayede a arrayınde yapılan bir değişiklikten yeni array etkilenmez.

a[0]=3

print(a)
print(y)
print(np.may_share_memory(a,y)) #bu fonksiyon sayesinde verilen arraylerin aynı memoryde tutulup tutulmadıgına bakılır. Boolean değer döndürür.

[3 2]
[1 2]
False


In [14]:
import numpy as np 
a = np.arange(0,10,1,dtype=complex).reshape(2,5) #bu fonksiyon ile belirlenen uzunlukta ve adım sayısında array oluşturulur.
# bu fonksiyon ile array yeniden şekillendirilir. 2 satır 5 sütun yaptık. arrayler yeterli eleman sayısına göre şekillendirilmelidir.
#dtype ile veri tipini seçeriz, int float complex vb
print(a)  

[[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]]


In [13]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #üc boyutlu bir dizi olusturmak 
print(a)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
a=np.array([[1,2],[3,4]])

b=np.full_like(a,12) #full_like benzer şekilde doldurarak array olusturur.a arrayı ile aynı boyutta ama içi 12 ile doldurulmuş yeni bir array verir.
print(b)

In [15]:
a=np.linspace(0,10,5) # 0'dan 10'a kadar giden ve 5 elemanlı olan array oluşturur. degerleri kendi belirler ve eşit aralıklı oluşturmaya calısır.
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
a=np.array([10,20,30,40,50])
b=np.array([5,10,15,20,25])
print(a-b)
c=np.sin(b)#b elemanının sinüs değerlerini alır.
d=np.power(b,2) # power fonksiyonu üs alır . b arrayının elemanlarının ikinci kuvvetini alarak yeni bir array olusturdu.
print(c)
print(d)

[ 5 10 15 20 25]
[-0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175]
[ 25 100 225 400 625]


In [22]:
#indexing slicing iterating
a=np.arange(0,20,1).reshape(4,5)
print(a)
print("-----------------------")
for row in a:
    print(row)

print("-----------------------")

print(a[:5:2 ,1:4:1]) # slicing ilk değerden başlar, son değeri dahil etmez, seçtiğimiz değere göre atlayarak yapabilir.bu şekilde arrayler içinde istediğimiz kısmı alabiliriz.
print("-----------------------")
for element in a.flat:
    print(element)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-----------------------
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
-----------------------
[[ 1  2  3]
 [11 12 13]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [23]:
a=np.arange(0,20,1).reshape(4,5)
print(a)
print("-----------------------")
print(a.ravel()) # a arrayinde ki tüm elemanları tek boyutlu bir array haline getirir.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-----------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
a=np.arange(0,20,1).reshape(4,5)
print(a.dtype)
print("-----------------------")
a=a.astype(np.float64) #arrayin tipini değiştirebiliriz. int to float yaptık.
print(a)
print(a.dtype)

int32
-----------------------
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
float64
