In [2]:
import numpy as np 

x=np.array([1,2,3,4,5]) #array komutunun içine bir list yerleştirerek array oluştururuz. arraylerde elemanlar aynı data tipindedir.
print(x)
print(type(x)) #arrayın sınıfına bakılır. ndarray.
print(x.shape) #her satır ve sütunda kaç eleman oldugunu gosterir.
print(x.size) # satır ve sütun sayısı çarpımı ile array büyükllüğünü gösterir.
print(x.ndim) # arrayın boyunu verir , tek boyutlu array oldugunu gosterdi.
print(x.nbytes) # veriyi depolamak içim kullanılan byte miktarını gösterir.
print(x.dtype) # elemanların veri tipini belirtir .


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5
1
20
int32


In [38]:
y=np.array([[1,2,3],[4,5,6]])
print(y)
print(type(y)) #arrayın sınıfına bakılır. ndarray.
print(y.shape) #her satır ve sütunda kaç eleman oldugunu gosterir. 2 satır 3 sütun var.   
print(y.size) # satır ve sütun sayısı çarpımı ile array büyüklüğünü gösterir.
print(y.ndim) # arrayın boyunu verir , iki boyutlu array oldugunu gosterdi.
print(y.nbytes) # veriyi depolamak içim kullanılan byte miktarını gösterir.
print(y.dtype) # elemanların veri tipini belirtir .

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
24
int32


In [39]:
x=np.array([1,2,3,4])   # array içinde ki veri tiplerini başka veri tipine dönüştürmek. int to float int to complex
print(x)
print(x.dtype) 

y=np.array([1,2,3,4],dtype=np.float64) 
print(y)
print(y.dtype) 

z=np.array([1,2,3,4],dtype=np.complex64) 
print(z)
print(z.dtype) 



[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


In [40]:
x=np.sqrt(np.array([-1,9,7,4], dtype=np.complex64)) #sqrt ile kök alınır.
print(x)
print(x.dtype)

print(x.real) #  kompleks verinin reel ve imajiner kısımlarını gosterir.
print(x.imag)

[0.       +1.j 3.       +0.j 2.6457512+0.j 2.       +0.j]
complex64
[0.        3.        2.6457512 2.       ]
[1. 0. 0. 0.]


In [41]:
x=np.array([1,3,5.2,6])
np.save('kaydedilen_array1',x)   # arrayı kaydeder.

y=np.load("kaydedilen_array1.npy") #kaydedilen arrayı çağırır.
print(y)

[1.  3.  5.2 6. ]


In [42]:
x1=np.zeros((2,3,4),dtype=np.int64) #sıfırlardan olusan bir array olusturmak
print(x1)

y1=np.ones((2,3)) #birlerden oluşan bir array oluşturmak 
print(y1)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
x=np.full((2,3),10)
print(x) # x array elemanlarını belirtilen veri ile doldurur.(10 ile doldurdu)

[[10 10 10]
 [10 10 10]]


In [44]:
q=np.empty((2,4)) #????
print(q)

[[1.97626258e-323 0.00000000e+000 1.06099790e-313 0.00000000e+000]
 [0.00000000e+000 2.96439388e-323 0.00000000e+000 1.48539705e-313]]


In [45]:
x=np.eye(4) #birim matris dondurur. 4x4
print(x) 

x=np.eye(5,k=1)
print(x)

x=np.eye(5,k=-2)
print(x)


y=np.identity(5) # birim matris olusturur.
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
x=np.diag([4,5,6,7]) #birim matrise verilen degerleri yerlestirir.
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [47]:
x=np.arange(1,10,2) # belirtilen değerler arasında istenilen sıralama ile array olusturur. 1den 10a 10u dahil etmeden 2şer 2şer
print(x)

[1 3 5 7 9]


In [48]:
y=np.linspace(1,30,13) #belirlenen değer aralıgında ve belirlenen sayıda aray olusturur.
print(y)

[ 1.          3.41666667  5.83333333  8.25       10.66666667 13.08333333
 15.5        17.91666667 20.33333333 22.75       25.16666667 27.58333333
 30.        ]


In [49]:
x=np.arange(0,10,1).reshape(2,5,1) # reshape ile matrisi arrayı yeniden sekillendirebiliriz. burada 2 adet 5x1 matris oluşturuldu.
print(x)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]


In [50]:
x=np.random.random((2,3)) #2x3 matris olusturur random şeklinde içinde ki değerler [0,1) 
print(x)

[[0.41274928 0.6756816  0.41297759]
 [0.02586496 0.90215802 0.67386902]]


In [36]:
x=np.random.randint(3,12,size=(3,2)) # belirlenen değerler arasında kaça kaç bir matris oluşturmak istersek bunu değerleri random şekilde verir.
print(x)

[[3 7]
 [3 6]
 [4 7]]


In [51]:
x=np.arange(5)
x[3]=20  #deger değistirme
print(x)

[ 0  1  2 20  4]


In [55]:
x=np.arange(20).reshape(4,5)
print(x)
print(x[1,2]) #1. satır 2. sütunda ki değeri gösterir
print(x[2,4]) #2. satır 4. sütunda ki değeri gösterir

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
7
14


In [56]:
x=np.arange(20).reshape(4,5)
x[3,4]=100 #3. satır 4. sütunu değistirdik
print(x)


[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 100]]


In [57]:
x=np.arange(6)
print(x)

y=np.delete(x,[0,1]) # 0 ıncı ve 1 inci indexi sildirir
print(y)
print(x)

[0 1 2 3 4 5]
[2 3 4 5]
[0 1 2 3 4 5]


In [63]:
#eğer axis=0 ise row yani satır değerleri işleme alınır, eğer axis=1 ise column yani sütun değerleri isleme alınır

x=np.arange(16).reshape(4,4)
print(x)

y=np.delete(x,1,axis=0) #x xin 1. satırını sildi. 
print(y)

z=np.delete(x,1,axis=1) #x xin 1. sütununu sildi. 
print(z)

q=np.delete(x,[1,2],axis=1) #x xin 1. ve 2. sütununu sildi. 
print(q)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]]
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]


In [3]:
x=np.arange(10)
print(x)
x=np.append(x,100) # arraye veri eklemek
print(x)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6   7   8   9 100]


In [4]:
x=np.arange(10)
x=np.append(x,[200,300])
print(x)

[  0   1   2   3   4   5   6   7   8   9 200 300]


In [8]:
x=np.arange(16).reshape(4,4)
print(x)
x=np.append(x,[[100,200,300,400]],axis=0) # birden fazla veri eklemek ,satır ekledik
print(x) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [100 200 300 400]]


In [10]:
x=np.arange(16).reshape(4,4)
print(x)
x=np.append(x,[[100],[200],[300],[400]],axis=1) # birden fazla veri eklemek ,sütun ekledik
print(x) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[  0   1   2   3 100]
 [  4   5   6   7 200]
 [  8   9  10  11 300]
 [ 12  13  14  15 400]]


In [17]:
x=np.arange(25).reshape(5,5)
print(x)
x=np.insert(x,2,[100,200,300,400,500],axis=0) #burada x in ikinci satırına ekledik.
print(x)
x=np.insert(x,2,[1000,2000,3000,4000,5000,6000],axis=1) #burada x in ikinci sütununa ekledik.
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 200 300 400 500]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
[[   0    1 1000    2    3    4]
 [   5    6 2000    7    8    9]
 [ 100  200 3000  300  400  500]
 [  10   11 4000   12   13   14]
 [  15   16 5000   17   18   19]
 [  20   21 6000   22   23   24]]


In [19]:
x=np.arange(4)
y=np.arange(16).reshape(4,4)

z=np.vstack((x,y)) #x i aldı ve y'nin üzerine koydu.dikey iliştirme verticalstack
print(z)

[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
x=np.arange(3)
y=np.arange(9).reshape(3,3)

z=np.hstack((x,y.reshape(9,))) #x i aldı ve y'nin başına koydu. yatay iliştirme.horizontal
print(z)

[0 1 2 0 1 2 3 4 5 6 7 8]


In [33]:
x=np.arange(10)
print(x[2:6])
print(x[3:])
print(x[:5])
print(x[-5:-2])

[2 3 4 5]
[3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7]


In [37]:
x=np.arange(25).reshape(5,5)
print(x[2:])
print()
print(x[1:4,2:4])   #iki boyutlu slicing
print()
print(x[::])
print()
print(x[:,3:])
print()



[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 7  8]
 [12 13]
 [17 18]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]



In [38]:
x=np.arange(16).reshape(4,4)
print(x)
y=np.copy(x[0:3,1:4])#aynı adreste tutulmamaları için copy kullanılır.
print(y)
print(np.shares_memory(x,y))#hafıza adresleri kontrol edilir.
y[0,0]=100
print(x)
print(y)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[100   2   3]
 [  5   6   7]
 [  9  10  11]]


In [41]:
x=np.linspace(1,21,11)
print(x)
y=np.array([2,4,7]) 
print(y)

print(x[y])  #x arrayı içinde ki 2. 4.ve 7. indexte ki değerleri slicing yaptı.

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]


In [43]:
x=np.arange(25).reshape(5,5)
print(x)
y=np.array([1,2])
print(y)

print(x[y,:]) # xin 1 ve 2. satırını aldık

print(x[:,y])# xin 1 ve 2. sütununu aldık


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [46]:
x=np.array([2,5,4,3,6,7])
y=np.array([1,3,8,9,5,0])

print(np.intersect1d(x,y)) # x ve y de ki ortak elemanlardan yeni bir array gosterir
print(np.setdiff1d(x,y)) # x in y den farklı elemanlarından olusan yeni array gosterir

print(np.union1d(x,y)) # x ve y nin birleşimini alır değerler tek sefer yazdırılır

print(np.in1d(x,y)) # x in y de de olan değerlerinin indexinde true dondurur. diğerlerini false



[3 5]
[2 4 6 7]
[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False False]


In [47]:
x=np.random.randint(1,10,size=(10,))
print(x)
print(np.sort(x)) #sıralar


[8 8 7 2 8 5 3 5 8 1]
[1 2 3 5 5 7 8 8 8 8]


In [50]:
x=np.random.randint(1,10,size=(9,)).reshape(3,3)
print(x)

print(np.sum(x))
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.min())
print(x.max())
print(x.argmin())
print(x.argmax())

[[4 8 4]
 [7 5 3]
 [9 4 8]]
52
[20 17 15]
[16 15 21]
3
9
5
6


In [55]:
x=np.random.randint(1,10,size=(8,))
print(x)
print(x.mean()) #ortalama

print(np.median(x)) # medyan alır ortada kalan

print(x.std()) # standart sapma alır 

[2 1 5 3 8 9 1 5]
4.25
4.0
2.8613807855648994


In [57]:
#Broadcasting
x=np.random.randint(1,10, size=(1,3))
print(x)
y=np.random.randint(1,10, size=(3,1))
print(y)

print(x+y)



[[8 6 3]]
[[7]
 [1]
 [9]]
[[15 13 10]
 [ 9  7  4]
 [17 15 12]]
